vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'

    mappings:

        product_images:
            uri_prefix: '%app.path.productimages%'
            upload_destination: '%kernel.project_dir%/public%app.path.productimages%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer